language: android
dist: trusty

jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

  matrix:
    - ANDROID_TARGET=21
    - ANDROID_TARGET=22

android:
  components:
    - android-21
    - android-22
    - android-28
    - build-tools-28.0.2
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22

cache:
  directories:
    - $HOME/.gradle/caches/4.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_TARGET --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - cd src
  - ./gradlew clean assemble -PdisablePreDex -q
  - ./gradlew connectedAndroidTest --console=plain
  - ./gradlew test --console=plain
